### ISSUE TITLE
Any known issues with the Online Management API commands?

### ISSUE THREAD

**Issue by reimondot** [WaelHamze/dyn365-ce-vsts-tasks#60] opened 2019-03-20 08:34 UTC
Hi,

Are there any current known issues with the Online Management API based commands like Enable Admin Mode or Backup instance? As I'm getting a strange "Unable to deserialize the response" error when using any of the Online Management API based commands.

The import/publish commands work fine.

Thanks

**Comment by WaelHamze** [comment] 2019-03-24 17:35
@reimondot they are working fine for me apart from restore. Are you still facing this issue?

**Comment by mw45156** [comment] 2019-04-11 08:20
We're facing the same issues as mentioned above, also the backup instance and Enable Admin Mode tasks. The version we're using is 10.*

Can anyone help?

2019-04-11T08:17:42.1702751Z ##[debug]Failed GetCrmInstances - ProcessRecord : 00:00:05.1961676
2019-04-11T08:17:42.3209482Z ##[debug]Message: Unable to deserialize the response. => Error converting value "Default" to type 'Microsoft.Xrm.Services.Admin.Client.Models.InstanceType'. Path '[1].Type', line 38, position 22. => Requested value 'Default' was not found.
2019-04-11T08:17:42.3230394Z ##[debug]Source	: Xrm.Online.Admin.Client
2019-04-11T08:17:42.3307909Z ##[debug]Method	: MoveNext
2019-04-11T08:17:42.3320668Z ##[debug]Date	: 4/11/2019
2019-04-11T08:17:42.3332302Z ##[debug]Time	: 8:17:42 AM
2019-04-11T08:17:42.3345539Z ##[debug]Error	: Unable to deserialize the response.
2019-04-11T08:17:42.3358455Z ##[debug]Stack Trace	: at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClient.<GetInstancesWithHttpMessagesAsync>d__30.MoveNext()
2019-04-11T08:17:42.3371195Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-04-11T08:17:42.3383883Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-11T08:17:42.3397055Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-11T08:17:42.3409535Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.<GetInstancesAsync>d__9.MoveNext()
2019-04-11T08:17:42.3421880Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-04-11T08:17:42.3433975Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-11T08:17:42.3447120Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-11T08:17:42.3460116Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.GetInstances(ID365CEAdminClient operations)
2019-04-11T08:17:42.3474854Z ##[debug]   at Microsoft.Xrm.OnlineManagementAPI.GetCrmInstances.ProcessRecord()
2019-04-11T08:17:42.3489945Z ##[debug]======================================================================================================================
2019-04-11T08:17:42.3504741Z ##[debug]Inner Exception Level 1	: 
2019-04-11T08:17:42.3518326Z ##[debug]Source	: Newtonsoft.Json
2019-04-11T08:17:42.3531994Z ##[debug]Method	: ReadJson
2019-04-11T08:17:42.3546826Z ##[debug]Date	: 4/11/2019
2019-04-11T08:17:42.3559372Z ##[debug]Time	: 8:17:42 AM
2019-04-11T08:17:42.3572599Z ##[debug]Error	: Error converting value "Default" to type 'Microsoft.Xrm.Services.Admin.Client.Models.InstanceType'. Path '[1].Type', line 38, position 22.
2019-04-11T08:17:42.3586699Z ##[debug]Stack Trace	: at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2019-04-11T08:17:42.3599700Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2019-04-11T08:17:42.3612481Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2019-04-11T08:17:42.3626202Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2019-04-11T08:17:42.3638921Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2019-04-11T08:17:42.3653093Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2019-04-11T08:17:42.3666114Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2019-04-11T08:17:42.3681419Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2019-04-11T08:17:42.3694339Z ##[debug]   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2019-04-11T08:17:42.3759767Z ##[debug]   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
2019-04-11T08:17:42.3760823Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClient.<GetInstancesWithHttpMessagesAsync>d__30.MoveNext()
2019-04-11T08:17:42.3762218Z ##[debug]======================================================================================================================

**Comment by reimondot** [comment] 2019-04-16 09:18
@WaelHamze What type of agent pool are you using? 

I've just restested this using both the backup and set admin mode tasks - Can confirm the same error is still being returned: _**Unable to deserialize the response**_

Not sure if it makes any difference but I'm using: https://admin.services.crm6.dynamics.com as I'm in Australia

**Comment by bwmodular** [comment] 2019-05-08 15:29
Hi @WaelHamze We have just started getting the same 'Unable to serialize the response.' in one of our pipelines. We have recently created a scheduled VSTS release pipeline which takes a backup of our production instance every night using the MSCRM Backup Online Instance task.

It worked for a few days, and then stopped working last week.

In the pipleine, we see the error 'Unable to serialize the response.'
We're not aware of anything changing in this instance which would cause this, and we can still backup the instance using the admin centre.
![image](https://user-images.githubusercontent.com/1889586/57387304-fd08bd00-71ad-11e9-9528-027a7121873a.png)
I'll let you know if we work out what the issue is...
(We are on crm4)

**Comment by bwmodular** [comment] 2019-05-08 15:42
@WaelHamze Doing a bit more digging, and turning system.debug on, it may be that the 'unable to serialise the response' is not the real error, but it is actually:
_Error converting value "Default" to type _'Microsoft.Xrm.Services.Admin.Client.Models.InstanceType'. Path '[2].Type', line 72, position 22. => Requested value 'Default' was not found.__
Here's a portion of the stack trace:
2019-05-08T15:35:09.4992026Z ##[debug]Connecting to API server: https://admin.services.crm4.dynamics.com/
2019-05-08T15:35:09.6398380Z ##[debug]Entering GetCrmInstances - ProcessRecord
2019-05-08T15:35:09.6398380Z ##[debug]Executing GetCrmInstances
2019-05-08T15:35:09.6867108Z ##[debug]Requesting Authentication - Start
2019-05-08T15:35:09.6867108Z ##[debug]Requesting Authority From server - Start
2019-05-08T15:35:09.8585834Z ##[debug]Requesting Authority From server - Finished : 00:00:00.1630600
2019-05-08T15:35:10.3644925Z ##[debug]Requesting Authentication - Completed : 00:00:00.6668990
2019-05-08T15:35:11.3288723Z ##[debug]Failed GetCrmInstances - ProcessRecord : 00:00:01.6834279
2019-05-08T15:35:11.3757463Z ##[debug]Message: Unable to deserialize the response. => **Error converting value "Default" to type 'Microsoft.Xrm.Services.Admin.Client.Models.InstanceType'. Path '[2].Type', line 72, position 22. => Requested value 'Default' was not found.**
2019-05-08T15:35:11.3757463Z ##[debug]Source	: Xrm.Online.Admin.Client
2019-05-08T15:35:11.3757463Z ##[debug]Method	: MoveNext
2019-05-08T15:35:11.3757463Z ##[debug]Date	: 08/05/2019
2019-05-08T15:35:11.3757463Z ##[debug]Time	: 16:35:11
2019-05-08T15:35:11.3757463Z ##[debug]Error	: Unable to deserialize the response.

Not sure if that actually helps...

**Comment by bwmodular** [comment] 2019-05-10 15:30
FWIW I've just used the Online management Api commandlet to create a backup using the same parameters and same credentials and it worked OK. So I'm pretty sure that the parameters I'm using are OK, and credentials are good, especially as this was working until 1 May and then stopped....
I know that doesn't help much but at least we can I think rule out user error.....

**Comment by bwmodular** [comment] 2019-05-13 12:03
I've also just now tried installing the OnlineManagementAPI PS module on our release server and running Backup-CrmInstance on there, and that also worked fine, so there's no coneectivity issues at play.
Just trying to rule out the most obvious causes.
@WaelHamze  Is there anything else I can try? Is it possible to run your tasks directly outside of the AzureDevops pipeline? Happy to try anything that will help understand the problem.

**Comment by bwmodular** [comment] 2019-06-10 10:31
@WaelHamze Trying to look at this again. In the online management api help file (in the Lib filder of your project) the valid instance types are listed as:-
- Production
- Sandbox
- Support
- Preview
- Trial

but from the error it seems as if _something_ is passing in the instance type as 'Default' which is causing the error. I'll try and dig into it further to see if I can work out where the Default value is coming from, but if you have any ideas, let me know....

**Comment by bwmodular** [comment] 2019-06-10 12:49
OK, more useful information. when I run the Get-CrmInstances command in Powershell ISE with the latest version of the Microsoft.Xrm.OnlineManagementAPI, it works fine. When I then uninstall the latest version of the Online Management API (1.1.0.9053) and run the version that is being called by the VSTS tasks in our pipeline (1.0.0), it fails with the error 'Unable to deserialize the response'.

So, it seems as if this issue might be fixed by updating the VSTS tasks to use the latest version of the Online Management API. I can see that both 1.0 and 1.1 are in your source code, but at runtime, in our case anyway, it refers to version 1.0.0.
Happy to help fix/test in any way I can.

**Comment by bwmodular** [comment] 2019-07-01 08:28
Hi @WaelHamze Do you have any thoughts on this? For now I've reverted to using a powershell command to take a regular backup, and this works fine. It seems to be that the VSTS task is using an older version of the OnlineManagementAPI, and I think this is causing the problem, as I can recreate the problem using this version of the API on my desktop, but when I use the latest version it works fine. The VSTS logs indidate that version 1.0 is being called, and version 1.1 does not give us this problem. Happy to help testing or providing any other information.

**Comment by WaelHamze** [comment] 2019-11-11 06:49
@bwmodular I believe this should be working, please re-open if any issues

**Closed by WaelHamze** 2019-11-11 06:49 UTC
Labels: help wanted

**Comment by bwmodular** [comment] 2019-11-11 10:10
Thanks  @WaelHamze yes I can confirm this is now working again, thanks.
