### ISSUE TITLE
Export solution is not working the first time of the day

### ISSUE THREAD

**Issue by Fernandobo21** [WaelHamze/dyn365-ce-vsts-tasks#193] opened 2020-07-14 08:33 UTC
hi,

Found an issue with the MSCRM Export Solution task.
The first time in the day that we tried to export a solution 
![TimeTaken](https://user-images.githubusercontent.com/4930082/87403548-4b3cfb80-c5bd-11ea-8589-de414786f8d4.png)
![TaskConfiguration](https://user-images.githubusercontent.com/4930082/87403595-57c15400-c5bd-11ea-9fbc-eaee33fe9f99.png)

always stay working more than 5 minutes.
then if we stop that execution and then retry, works fine and in only 2 minutes.

Attached an image with the configuration and another image with the transcurred time.

Thanks in advance.

**Comment by Guyanthalas** [comment] 2020-07-15 16:35
I was having the same problem yesterday. It also seems that if there is sufficient time between runs it still fails. The first one failed and I tried to re-run it some hours later and it failed again (time-out). It wasn't until I tried doing it today that I went looking to see if anyone else was having this issue, and found this. Sure enough, once I canceled the task mid run and immediately re-ran, it worked on the re-run.

**Comment by mattp65** [comment] 2020-07-15 16:56
See [https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues/183](url)

**Comment by WaelHamze** [comment] 2020-07-16 07:24
@Fernandobo21 @Guyanthalas 

Might be worth trying to add the publish customizations task before the export of the solution to see if it fixes the problem?

**Comment by Jose8bike** [comment] 2020-07-16 14:34
@WaelHamze I added the "Publish Customization" step before exporting the solution, and it worked.

![PipelineExportSolution](https://user-images.githubusercontent.com/68286598/87684197-42495700-c782-11ea-8f5d-d56f60cab56b.PNG)

Even so, I do not understand well why before it did not work the first time and the following ones did.

Thank you very much for the help.

**Comment by Guyanthalas** [comment] 2020-07-22 20:36
@WaelHamze Mine was Publish/increment version/Export... changed it to Increment/Publish/Export and the problem persists.

**Comment by Guyanthalas** [comment] 2020-07-23 18:30
Update, I don't think this is on your code. As a test, I installed the Power Platform Tools and used their "export solution" task. It also stalls out. Re-run works perfectly. Still no idea why it is happening, but at least I can take it off your shoulders to fix.

**Comment by mattp65** [comment] 2020-07-23 19:13
Check the Issue I linked to above. It has an alternate PowerShell script that you can try.

**Comment by WaelHamze** [comment] 2020-09-07 06:57
Closing this as a duplicate of #183

**Closed by WaelHamze** 2020-09-07 06:57 UTC
Labels: duplicate, product issue, under investigation
