### ISSUE TITLE
Deploying Managed Solution Upgrade

### ISSUE THREAD

**Issue by mrmwink** [WaelHamze/dyn365-ce-vsts-tasks#218] opened 2020-10-16 12:49 UTC
Hi,

I'm currently using the Solution Upgrade using the holding solution and then Upgrade Solution task, which has been working fine but takes much longer as when doing the straight Upgrade available through the UI, the question is can I replicate the straight solution upgrade that is the default option when manually updating through the UI, via a task within the DevOps pipeline!?

Thanks

Mike

**Comment by mattp65** [comment] 2020-10-16 14:15
Part of the problem is that when you run this from the UI, it submits the job in the background and you aren't always actually waiting for it to complete since the UI times out while it the job still runs to completion. When you run it from a pipeline, it is actually waiting for it to complete. This is important from an automation perspective as the org can't handle another Solution type activity (Import, Upgrade, Publish, etc) while one is running.

**Comment by mrmwink** [comment] 2020-10-16 14:57
That makes sense, I just tried in the UI and then tried to deploy a 2nd solution to the environment and it fell over spectacularly as the first one was running in the background!!

**Comment by WaelHamze** [comment] 2020-11-16 19:04
@mattp65 @mrmwink thanks for this. Closing the issue. Please re-open if you have any further questions.

**Closed** 2020-11-16 19:04 UTC
Labels: question
