### ISSUE TITLE
Export Solution task suffers System.OperationCanceledException when run on a schedule

### ISSUE THREAD

**Issue by sirjameswood** [WaelHamze/dyn365-ce-vsts-tasks#171] opened 2020-04-15 08:50 UTC
Hey,

I have a build pipeline with the following tasks:

- Tool installer.
- Publish customisations.
- Set version - solution 1.
- Set version - solution 2.
- Set version - solution 3.
- Export solution - solution 1.
- Export solution - solution 2.
- Export solution - solution 3.
- Publish pipeline artifact.

When I run the pipeline on demand everything works correctly.

When I run the pipeline on a schedule (1 AM every night), the first Export Solution step fails. It just never seems to complete and the agent then cancels the step. 

The log from the step is below.

Is there a way I can access a more detailed log? E.g. The [Tracing in XRM Tooling](*https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/configure-tracing-xrm-tooling*)?

Any pointers would be appreicated,

Thanks,

James

```
2020-04-15T00:02:06.7533837Z Exporting Unmanaged Solution
2020-04-15T00:02:06.7684553Z ##[debug]PS Version: 5.1.17763.1007
2020-04-15T00:02:06.7766854Z ##[debug]Microsoft.Xrm.Sdk.dll - Version : 9.0.44.892
2020-04-15T00:02:06.7795695Z ##[debug]Microsoft.Xrm.Tooling.Connector.dll - Version : 4.0.0.47
2020-04-15T00:02:06.7822521Z ##[debug]Current Security Protocol: Tls, Tls11, Tls12
2020-04-15T00:02:06.7851255Z ##[debug]Modified Security Protocol: Tls, Tls11, Tls12
2020-04-15T00:02:06.7941655Z ##[debug]Connecting to CRM [attempt 1]
2020-04-15T00:02:07.6307033Z ##[debug]Connection to CRM Established using OrganizationWebProxyClient
2020-04-15T00:02:07.6363287Z ##[debug]Exporting Solution: Solution 1
2020-04-15T00:30:59.5076450Z ##[debug]Re-evaluate condition on job cancellation for step: 'Export Solution: Solution 1'.
2020-04-15T00:31:09.6617490Z ##[error]The operation was canceled.
2020-04-15T00:31:09.6640276Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-04-15T00:31:09.6645664Z ##[section]Finishing: Export Solution: Solution 1
```

**Comment by do215** [comment] 2020-04-17 12:57
This was originally posted on the old repository.

I have a similar issue, which has surfaced during the last couple of months. We have had a CI pipeline for some time now without any prior timeout errors regarding the export request task, but this has suddenly become a recurring issue.

I have investigated the issue, and it seems that when the export request takes longer than ~250 seconds it will cause the CI task to fail and apparently not receive the response and lead to a timeout. When the request takes around 50-90 seconds the export task worker will receive the response and no timeout will occur.

This behavior did **not** occur in a build on 16th of march, but it did occur on 26th of march.
![image](https://user-images.githubusercontent.com/63789842/79453858-8e9dc300-7fea-11ea-99eb-fa7ce6cb25c8.png)

I did some more digging, and in the code, the default timeout is set to 120 seconds, this seems likely to be what is causing the issue to occur for our exports, but I can't be sure unless I spend some more time digging.we do set a timeout ourselves through the Connection Timeout variable, but this no longer seem to work.

**Comment by sirjameswood** [comment] 2020-04-17 15:08
Looking at the solution history I am seem to be experiencing the same behaviour.

**Comment by sirjameswood** [comment] 2020-04-17 15:48
I've increased the timeout in the export task, and by reviewing the verbose log and code it would seem to be applied. I'll see how I get on over the next few days and see if this resolves the issue.

**Comment by WaelHamze** [comment] 2020-04-20 07:10
@sirjameswood it seems like your issue could be related to the agent itself. I suspect something might be running at the same time. Do you use hosted or private agents?

Have you tried to make this run at 2am instead?

**Comment by sirjameswood** [comment] 2020-04-20 09:18
Hosted agent, running on Windows-2019. 

I've tried a couple of different times with the same outcome.

Increasing the timeout hasnt appeared to resolve the issue either.

**Comment by sirjameswood** [comment] 2020-04-20 09:28
Details from the last run. Solution History in Dynamics shows success.

![image](https://user-images.githubusercontent.com/28485879/79736225-61565b00-82f1-11ea-8478-e9a8be367f8c.png)

Extracts from log from export task:

2020-04-20T00:02:13.1424408Z Task         : Export Solution
2020-04-20T00:02:13.1425490Z Author       : Wael Hamze
...
2020-04-20T00:02:14.4446079Z ##[debug]Timeout = 600
...
2020-04-20T00:02:15.6923655Z ##[debug]Connection to CRM Established using OrganizationWebProxyClient
2020-04-20T00:02:15.6973048Z ##[debug]Exporting Solution: Build
2020-04-20T00:31:05.2675815Z ##[debug]Re-evaluate condition on job cancellation for step: 'Export Solution: Build'.
2020-04-20T00:31:15.4303409Z ##[error]The operation was canceled.
2020-04-20T00:31:15.4324164Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()

**Comment by WaelHamze** [comment] 2020-04-20 16:22
@sirjameswood seems like the error is happening close to 30 minutes. Is the solution that big? Normally this should be very quick.

**Comment by do215** [comment] 2020-04-21 08:10
@sirjameswood maybe we should clarify to @WaelHamze  that the issue is not related to the build being scheduled. It is related to the behavior where an export request takes longer than X seconds (my guess is the hard coded default 120 seconds). This happens periodically (and probably more often on scheduled builds) since D365 has some kind of performance optimization, where it takes a while for the background tasks to start up again from sleep. Normally our export request takes around 50 seconds, and when this is the case everything works fine.

If you need a case to reproduce I would suggest to create an export task in a build pipeline, where the export request duration in D365 exceeds the hard coded default timeout of 120 seconds. Either try to do that or perhaps make a branch where you change the hard coded default value to something very small, and make a build pipeline with an export request, and see if the behaviour is the same when the duration exceeds the default timeout - regardless of what the build pipeline timeout variable is set to.

**Comment by sirjameswood** [comment] 2020-04-21 10:14
@do215 yes, you are correct.

@WaelHamze, this issue tends to happen most often on scheduled runs, but I've actually just had it fail when run on-demand this morning.

By viewing the Solution History I can see all exports are successful, just some take a long time - but far less than 30 minutes.

![image](https://user-images.githubusercontent.com/28485879/79853927-94b3eb00-83c0-11ea-9264-45d0f06002f5.png)

The pipeline is cancelled by the agent at 30 minutes due to the timeout I set (by default it runs for an hour).

![image](https://user-images.githubusercontent.com/28485879/79854149-eb212980-83c0-11ea-9fbc-e166745b0890.png)

It seems that is the export takes more than a couple of minutes, the build agent get's stuck (even though the export is successful), until its eventually cancelled by agent timeout.

**Comment by CBrams** [comment] 2020-05-15 16:16
Yes, we have the same issue. A solution took ~360 seconds to complete the export on a fluke (possibly just spinning up the service again). Pipeline failed on timeout (1 hour by default), since it didn't get the finish signal from the task.

Next run, with no changes, the solution took only ~60 seconds to export this time around, and the pipeline completed in good order.

It would be best if we can change the hardcoded timeout of 120 seconds @do215 mentions, but otherwise if the task would just fail faster, we could at least get the pipeline running again, without wasting a lot of idle-time.

**Comment by WaelHamze** [comment] 2020-05-28 06:50
@CBrams have you tried to change the Connection Timeout in the Export Task?

**Comment by CBrams** [comment] 2020-05-28 15:51
@WaelHamze Yes, it is set to 1800 seconds. The step acknowledges this in the debug statements that it logs, saying 
```

##[debug]INPUT_CRMCONNECTIONTIMEOUT: '1800'
##[debug] Converted to int: 1800

```
I cancelled the step after a total of 33 minutes, but the control option timeout is set to 0 (infinite), meaning that it will likely not be cancelled by the server.

**Comment by WaelHamze** [comment] 2020-09-07 06:55
Closing this as a duplicate of #183

**Closed by WaelHamze** 2020-09-07 06:55 UTC
Labels: duplicate, product issue, under investigation
