### ISSUE TITLE
MSCRM Pack Solution not including sitemap

### ISSUE THREAD

**Issue by azavos** [WaelHamze/dyn365-ce-vsts-tasks#56] opened 2019-03-11 13:15 UTC
Hi,

We're using your 365 tools in azure devops and have noticed that the MSCRM Pack Solution step (v. 10.0.4) is not including the contents of the AppModuleSiteMaps directory in the packaged solution zip files.

The `<AppModuleSiteMaps>` tag is empty. When the solution is imported an error "Cannot add a Root Component <nameofcomponent> of type 62 because it is not in the target system" is generated because of this.

Using version 8.2.0.820 of the solutionpackager.exe provided in the SDK seems to resolve the problem (earlier versions may also work this just happens to be the version I have available).

**Comment by WaelHamze** [comment] 2019-03-12 21:24
@azavos which version of Dynamics are you using and which version of SDK have you selected on the task?

**Comment by WaelHamze** [comment] 2019-03-12 21:26
If you select 8.2 then the solutionpackager.exe is the same version as you selected above

**Comment by azavos** [comment] 2019-03-13 16:01
using dynamics365 v

**Comment by lheng18** [comment] 2019-03-25 05:09
I encountered the same issue. I use Dynamics v9.1 0.2859 and SDK v9 and  MSCRM Pack Solution step (v. 10.*) and it doesn't pack the contents of the AppModuleSiteMaps directory in the packaged solution zip files. I tried configuring to pack task/step to use the v8.2 SDK but got error. However I am able to pack AppModuleSiteMaps into customization file using SPKL containing latest SDK assembly. I just can't pack it using SCRM Pack Solution step (v. 10.*) . Thanks!
<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/48900629/54896413-1bcb2280-4e92-11e9-845f-fcb935218b17.PNG">

**Comment by WaelHamze** [comment] 2019-03-27 21:44
@lheng18 the Task is using the latest v9 SDK 9.0.2.12 to Pack: https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools

I think we need to figure out whether the issue is with the pack or unpack. Are you able to download the above SDK and unpack -> pack the solution using the command line and see what you get?

**Comment by lheng18** [comment] 2019-03-27 23:24
I used SPKL and updated CRM assemblies to the version you mentioned using NeGet. I unpacked the solution as  managed into files. Then I used SPKL to pack the files back to a managed zip file fine. The AppModuleSiteMap node contains context in the customization file of the managed solution. But if I used the Tool Task to back it to a managed solution file, it missed the content of AppModuleSiteMap.

Thanks!

**Comment by lheng18** [comment] 2019-03-27 23:32
Unpacked Folders:
![image](https://user-images.githubusercontent.com/48900629/55118869-cd01d080-50bd-11e9-906f-13d544dd9173.png)
Pack Log Screenshots:
![image](https://user-images.githubusercontent.com/48900629/55119055-692bd780-50be-11e9-8dc9-2c660cda46cd.png)
It didn't process the AppModuleSiteMap and processed the next item.
![image](https://user-images.githubusercontent.com/48900629/55119031-4d283600-50be-11e9-94ca-8b92ec4a92fe.png)

**Comment by lheng18** [comment] 2019-03-28 22:33
Used the Solution Packager from the above version SDK to pack the solution file and I got the same issue. Wonder how SPKL fixed it.

The repo does have files checked in and the files are getting downloaded on the build server.

**Comment by lheng18** [comment] 2019-03-29 04:17
Identified the root cause. I found out SPKL doesn't use the latest Dynamics SDK Assembly even though I use NuGet to get latest SPKL. It uses the Solution Packager in Microsoft.CrmSdk.CoreTools.9.0.0.7 folder comes with its package according to the log file. I run the Solution Packager  in the folderMicrosoft.CrmSdk.CoreTools.9.0.0.7.  I was able to pack the SiteMap. The following is the snippet of the log file. The tools processed AppModuleSiteMaps

Processing Component: AppModuleSiteMaps
Reading: C:\Users\hlit\Source\Repos\<ProjectName>\Chevron.Core.SolutionPackageManaged\package\AppModuleSiteMaps\chevron_WOPR\AppModuleSiteMap.xml**
Processing Component: AppModules

I think it is Microsoft Dynamics SDK latest assembly v9 SDK 9.0.2.12  issue. The SolutuonPackager comes with it doesn't pack <AppModuleSiteMaps>. In your tool, can I use V9 earlier version? It seems only allows V8 version or V9 version. I tried V8,  it threw error.

Thanks!

**Comment by lheng18** [comment] 2019-03-29 04:22
Identified the root cause. I found out SPKL doesn't use the latest Dynamics SDK Assembly even though I use NuGet to get latest SPKL. It uses the Solution Packager in Microsoft.CrmSdk.CoreTools.9.0.0.7 folder comes with its package according to the log file. I run the Solution Packager in the folderMicrosoft.CrmSdk.CoreTools.9.0.0.7. I was able to pack the SiteMap. The following is the snippet of the log file. The tools processed AppModuleSiteMaps

Processing Component: AppModuleSiteMaps
Reading: C:\Users\hlit\Source\Repos<ProjectName>\Core.SolutionPackageManaged\package\AppModuleSiteMaps<SiteMap name>\AppModuleSiteMap.xml**
Processing Component: AppModules

I think it is Microsoft Dynamics SDK latest assembly v9 SDK 9.0.2.12 issue. The SolutuonPackager comes with it doesn't pack . In your tool, can I use V9 earlier version? It seems only allows V8 version or V9 version. I tried V8, it threw error.

Thanks!

**Comment by WaelHamze** [comment] 2019-04-02 19:21
@lheng18 there is another task called "MSCRM Pack Solution Using Config", with this one you can specify your own version of the solution packager, an example config is here: https://github.com/WaelHamze/dyn365-ce-devops-sample/blob/master/Sample/Xrm.CI.Framework.Sample/Customizations/Solutions/PackConfig.json

You could give this a try when the version is out and it will give you option to remain on older version if needed. I may add this feature to the other task as well.

Note that will work as long as the parameters don't change between versions.

**Comment by lheng18** [comment] 2019-04-03 03:23
@WaelHamze Where do I put the Solution Packager version number? Is it    "Version": "#{BuildVersion}#" in the JSON config file? It looks like for Solution version.

Thanks!

**Comment by WaelHamze** [comment] 2019-04-03 19:13
Yes the version is if you want to set a static version or you can replace at runtime with a value from build

The path you can set on the task itself

![image](https://user-images.githubusercontent.com/11046518/55506308-fdf97c80-564c-11e9-9d14-7d716d1cd54e.png)

**Comment by lheng18** [comment] 2019-04-04 01:42
Thanks @WaelHamze ! Just received notification from Microsoft. They have released a new version of SDK 9.0.3.1 which addressed this issue. You can update your tool.

**Comment by lheng18** [comment] 2019-04-04 02:10
@WaelHamze found out this release has still Not resolved the issue.

**Comment by WaelHamze** [comment] 2019-04-04 07:24
@lheng18 tool has already been updated. Any luck with getting the other task open on the previous version?

I presume you have a case open with MS?

**Comment by lheng18** [comment] 2019-04-04 13:29
@WaelHamze Yes. I do work with Microsoft. Thanks!

**Comment by lheng18** [comment] 2019-04-11 13:54
@WaelHamze I was able to use the previous version using the MSCRM Pack Solution Using Config build task. Thanks!

**Comment by lheng18** [comment] 2019-06-06 13:03
@WaelHamze Microsoft has fixed in issue in the latest Solution Packager. Now the latest is 9.0.3.4. but when I switch to use the Pack Solution  Build Task and got the same issue, then I noticed it still uses the 9.0.3.1 version. Does the Build task always use the latest version? if not do I have to download the new Build Task? How can I get it refereshed? 
==============================================================================
Task         : MSCRM Pack Solution
Description  : Packages a CRM Solution using SolutionPackager.exe
Version      : 10.0.4
Author       : Wael Hamze
Help         : Solution files must be checked-in to source control
==============================================================================
Packing Solution from Path: D:\a\1\s\mysolution\package
Packing Solution Name: MySolution
Solution Packager Version: 9.0.3.1

Thanks!

**Comment by lheng18** [comment] 2019-06-11 03:23
@WaelHamze Will you be using the latest Solution Packager in new release?

**Comment by lheng18** [comment] 2019-06-14 15:07
@WaelHamze when will the latest release supporting above 9.0.3.1 version which fixed the bug available? Thanks!

**Comment by WaelHamze** [comment] 2019-06-18 18:50
@lheng18 Released

**Closed by WaelHamze** 2019-06-18 18:50 UTC
Labels: product issue, question

**Comment by lheng18** [comment] 2019-06-18 19:43
@WaelHamze Thank you!

**Comment by LycraLout** [comment] 2019-09-30 12:19
Since the last update to solutionpackager 9.1.0.13 I have been suffering from this problem again. I''m using v9 of the task to get around it in the meantime.
