### ISSUE TITLE
Solution Export Timeout

### ISSUE THREAD

**Issue by nishshade** [WaelHamze/dyn365-ce-vsts-tasks#205] opened 2020-09-02 11:03 UTC
i am using the Export Solution Task for solution export as both managed and unmanaged. The Build fails regularly after running its course. On successful completion the Export of all the 4 solutions takes no more than 15 minutes. We are running it on a schedule at 7PM BST every night. We have now reduced the build to timeout in 30 minutes to save time as we know about the failure is bound to happen. Strangely enough when we re run it, there are no issues and it goes through successfully.

When we let it run indefinitely it failed saying "Organisation.svc has timed out". I have raised a support request with Microsoft for this but they closed it saying that it' not their issue. Any help would be appreciated.

**Comment by mattp65** [comment] 2020-09-02 15:16
See #183

**Comment by nishshade** [comment] 2020-09-02 16:17
> See #183

Could not find a solution though. Am i looking at the right place?

**Comment by WaelHamze** [comment] 2020-09-07 06:54
Closing this as a duplicate of #183

**Closed by WaelHamze** 2020-09-07 06:54 UTC
Labels: duplicate
